-- Home-services categories, round 4 (2026-10-08): long tail from NY/IL/GA/MA/PA data. Home trades to their category, everything else to Other.
INSERT INTO category_map(sub_slug,sub,main,updated_at) VALUES
('paving-contractor','Paving contractor','General Contractors',0),
('asphalt-contractor','Asphalt contractor','General Contractors',0),
('garage-builder','Garage builder','General Contractors',0),
('metal-construction-company','Metal construction company','General Contractors',0),
('sheet-metal-contractor','Sheet metal contractor','General Contractors',0),
('shed-builder','Shed builder','General Contractors',0),
('sunroom-contractor','Sunroom contractor','General Contractors',0),
('modular-home-builder','Modular home builder','General Contractors',0),
('building-consultant','Building consultant','General Contractors',0),
('building-designer','Building designer','General Contractors',0),
('construction','Construction','General Contractors',0),
('debris-removal-service','Debris removal service','General Contractors',0),
('railroad-contractor','Railroad contractor','General Contractors',0),
('crane-service','Crane service','General Contractors',0),
('pond-contractor','Pond contractor','General Contractors',0),
('steel-fabricator','Steel fabricator','General Contractors',0),
('metal-fabricator','Metal fabricator','General Contractors',0),
('welder','Welder','General Contractors',0),
('painting','Painting','Handyman & Remodeling',0),
('dry-wall-contractor','Dry wall contractor','Handyman & Remodeling',0),
('plasterer','Plasterer','Handyman & Remodeling',0),
('property-maintenance','Property maintenance','Handyman & Remodeling',0),
('interior-designer','Interior designer','Handyman & Remodeling',0),
('interior-decorator','Interior Decorator','Handyman & Remodeling',0),
('millwork-shop','Millwork shop','Handyman & Remodeling',0),
('wood-floor-installation-service','Wood floor installation service','Handyman & Remodeling',0),
('shower-door-shop','Shower door shop','Handyman & Remodeling',0),
('home-help','Home help','Handyman & Remodeling',0),
('glass-shop','Glass shop','Handyman & Remodeling',0),
('awning-supplier','Awning supplier','Handyman & Remodeling',0),
('screen-repair-service','Screen repair service','Handyman & Remodeling',0),
('electric-motor-repair-shop','Electric motor repair shop','Electricians',0),
('electrical-engineer','Electrical engineer','Electricians',0),
('home-automation-company','Home automation company','Electricians',0),
('solar-energy-equipment-supplier','Solar energy equipment supplier','Electricians',0),
('solar-panel-maintenance-service','Solar panel maintenance service','Electricians',0),
('electric-vehicle-charging-station-contractor','Electric vehicle charging station contractor','Electricians',0),
('lighting-consultant','Lighting consultant','Electricians',0),
('energy-equipment-and-solutions','Energy equipment and solutions','Electricians',0),
('elevator-service','Elevator service','Electricians',0),
('home-cinema-installation','Home cinema installation','Electricians',0),
('heating-oil-supplier','Heating oil supplier','Heating & Air Conditioning',0),
('air-conditioning-system-supplier','Air conditioning system supplier','Heating & Air Conditioning',0),
('boiler-supplier','Boiler supplier','Heating & Air Conditioning',0),
('fire-protection-service','Fire protection service','Home Security',0),
('fire-protection-equipment-supplier','Fire protection equipment supplier','Home Security',0),
('fire-protection-system-supplier','Fire protection system supplier','Home Security',0),
('fire-alarm-supplier','Fire alarm supplier','Home Security',0),
('fire-protection-consultant','Fire protection consultant','Home Security',0),
('security-service','Security service','Home Security',0),
('appliance-store','Appliance store','Home Supply Stores',0),
('bathroom-supply-store','Bathroom supply store','Home Supply Stores',0),
('hot-tub-store','Hot tub store','Home Supply Stores',0),
('lumber-store','Lumber store','Home Supply Stores',0),
('tool-store','Tool store','Home Supply Stores',0),
('equipment-rental-agency','Equipment rental agency','Home Supply Stores',0),
('tool-rental-service','Tool rental service','Home Supply Stores',0),
('paint-store','Paint store','Home Supply Stores',0),
('tile-store','Tile store','Home Supply Stores',0),
('kitchen-supply-store','Kitchen supply store','Home Supply Stores',0),
('marble-supplier','Marble supplier','Home Supply Stores',0),
('stone-supplier','Stone supplier','Home Supply Stores',0),
('window-treatment-store','Window treatment store','Home Supply Stores',0),
('water-pump-supplier','Water pump supplier','Home Supply Stores',0),
('hose-supplier','Hose supplier','Home Supply Stores',0),
('appliance-parts-supplier','Appliance parts supplier','Home Supply Stores',0),
('light-bulb-supplier','Light bulb supplier','Home Supply Stores',0),
('refrigerator-store','Refrigerator store','Home Supply Stores',0),
('vacuum-cleaner-store','Vacuum cleaner store','Home Supply Stores',0),
('lawn-mower-store','Lawn mower store','Home Supply Stores',0),
('construction-equipment-supplier','Construction equipment supplier','Home Supply Stores',0),
('outdoor-furniture-store','Outdoor furniture store','Home Supply Stores',0),
('grill-store','Grill store','Home Supply Stores',0),
('landscape-architect','Landscape architect','Lawn, Landscaping & Trees',0),
('plant-nursery','Plant nursery','Lawn, Landscaping & Trees',0),
('asbestos-testing-service','Asbestos testing service','Water Damage Restoration',0),
('swimming-pool','Swimming pool','Pools & Spas',0),
('portable-toilet-supplier','Portable toilet supplier','Moving & Junk Removal',0),
('recycling-center','Recycling center','Moving & Junk Removal',0),
('shredding-service','Shredding service','Moving & Junk Removal',0),
('adult-education-school','Adult education school','Other',0),
('agricultural-product-wholesaler','Agricultural product wholesaler','Other',0),
('antique-store','Antique store','Other',0),
('apprenticeship-center','Apprenticeship center','Other',0),
('architectural-designer','Architectural designer','Other',0),
('attorney','Attorney','Other',0),
('auction-house','Auction house','Other',0),
('audio-visual-consultant','Audio visual consultant','Other',0),
('audio-visual-equipment-supplier','Audio visual equipment supplier','Other',0),
('audiovisual-equipment-rental-service','Audiovisual equipment rental service','Other',0),
('auto-insurance-agency','Auto insurance agency','Other',0),
('auto-parts-store','Auto parts store','Other',0),
('auto-restoration-service','Auto restoration service','Other',0),
('automation-company','Automation company','Other',0),
('bakery','Bakery','Other',0),
('bar','Bar','Other',0),
('barber-shop','Barber shop','Other',0),
('bee-relocation-service','Bee relocation service','Other',0),
('boat-repair-shop','Boat repair shop','Other',0),
('bookkeeping-service','Bookkeeping service','Other',0),
('brake-shop','Brake shop','Other',0),
('business-center','Business center','Other',0),
('business-development-service','Business development service','Other',0),
('business-networking-company','Business networking company','Other',0),
('business-related','Business related','Other',0),
('cable-company','Cable company','Other',0),
('car-detailing-service','Car detailing service','Other',0),
('car-stereo-store','Car stereo store','Other',0),
('cardiologist','Cardiologist','Other',0),
('cell-phone-store','Cell phone store','Other',0),
('child-care-agency','Child care agency','Other',0),
('civil-engineer','Civil engineer','Other',0),
('cleaners','Cleaners','Other',0),
('cleaning-products-supplier','Cleaning products supplier','Other',0),
('college','College','Other',0),
('computer-consultant','Computer consultant','Other',0),
('computer-repair-service','Computer repair service','Other',0),
('computer-service','Computer service','Other',0),
('computer-support-and-services','Computer support and services','Other',0),
('computer-training-school','Computer training school','Other',0),
('consultant','Consultant','Other',0),
('convenience-store','Convenience store','Other',0),
('county-government-office','County government office','Other',0),
('credit-reporting-agency','Credit reporting agency','Other',0),
('crime-victim-service','Crime victim service','Other',0),
('delivery-service','Delivery service','Other',0),
('design-engineer','Design engineer','Other',0),
('diesel-engine-repair-service','Diesel engine repair service','Other',0),
('distribution-service','Distribution service','Other',0),
('divorce-lawyer','Divorce lawyer','Other',0),
('doctor','Doctor','Other',0),
('donations-center','Donations center','Other',0),
('dry-cleaner','Dry cleaner','Other',0),
('education-center','Education center','Other',0),
('educational-institution','Educational institution','Other',0),
('electric-bicycle-store','Electric bicycle store','Other',0),
('electric-motor-store','Electric motor store','Other',0),
('electric-vehicle-charging-station','Electric vehicle charging station','Other',0),
('electronic-parts-supplier','Electronic parts supplier','Other',0),
('electronics-company','Electronics company','Other',0),
('electronics-engineer','Electronics engineer','Other',0),
('electronics-manufacturer','Electronics manufacturer','Other',0),
('electronics-repair-shop','Electronics repair shop','Other',0),
('electronics-store','Electronics store','Other',0),
('electronics-wholesaler','Electronics wholesaler','Other',0),
('elementary-school','Elementary school','Other',0),
('emergency-room','Emergency room','Other',0),
('energy-advisory-service','Energy advisory service','Other',0),
('energy-supplier','Energy supplier','Other',0),
('environmental-consultant','Environmental consultant','Other',0),
('equipment-supplier','Equipment supplier','Other',0),
('event-technology-service','Event technology service','Other',0),
('family-service-center','Family service center','Other',0),
('fire-department-equipment-supplier','Fire department equipment supplier','Other',0),
('fire-station','Fire station','Other',0),
('foundry','Foundry','Other',0),
('fuel-supplier','Fuel supplier','Other',0),
('furniture-store','Furniture store','Other',0),
('game-store','Game store','Other',0),
('gas-company','Gas company','Other',0),
('gas-station','Gas station','Other',0),
('golf-course','Golf course','Other',0),
('government','Government','Other',0),
('government-office','Government office','Other',0),
('gym','Gym','Other',0),
('hair-salon','Hair salon','Other',0),
('high-school','High school','Other',0),
('holding-company','Holding company','Other',0),
('home-health-care-service','Home health care service','Other',0),
('home-help-service-agency','Home help service agency','Other',0),
('home-theater-store','Home theater store','Other',0),
('hotel','Hotel','Other',0),
('hydraulic-repair-service','Hydraulic repair service','Other',0),
('immigration-attorney','Immigration attorney','Other',0),
('industrial-design-company','Industrial design company','Other',0),
('industrial-equipment-supplier','Industrial equipment supplier','Other',0),
('internet-marketing-service','Internet marketing service','Other',0),
('internet-service-provider','Internet service provider','Other',0),
('janitorial-equipment-supplier','Janitorial equipment supplier','Other',0),
('juice','Juice','Other',0),
('law-firm','Law firm','Other',0),
('learning-center','Learning center','Other',0),
('lighting-manufacturer','Lighting manufacturer','Other',0),
('local-government-office','Local government office','Other',0),
('logistics-service','Logistics service','Other',0),
('machining-manufacturer','Machining manufacturer','Other',0),
('marina','Marina','Other',0),
('marine-surveyor','Marine surveyor','Other',0),
('meat-processor','Meat processor','Other',0),
('medical-clinic','Medical clinic','Other',0),
('medical-laboratory','Medical laboratory','Other',0),
('mexican','Mexican','Other',0),
('middle-school','Middle school','Other',0),
('mobile-home-dealer','Mobile home dealer','Other',0),
('mobile-phone-repair-shop','Mobile phone repair shop','Other',0),
('mobility-equipment-supplier','Mobility equipment supplier','Other',0),
('musical-instrument-store','Musical instrument store','Other',0),
('newspaper-publisher','Newspaper publisher','Other',0),
('office-furniture-store','Office furniture store','Other',0),
('oil-and-natural-gas-company','Oil & natural gas company','Other',0),
('oil-field-equipment-supplier','Oil field equipment supplier','Other',0),
('oil-refinery','Oil refinery','Other',0),
('orchestra','Orchestra','Other',0),
('outdoor-sports-store','Outdoor sports store','Other',0),
('park','Park','Other',0),
('performing-arts-theater','Performing arts theater','Other',0),
('pet-store','Pet store','Other',0),
('plastic-fabrication-company','Plastic fabrication company','Other',0),
('plastic-injection-molding-service','Plastic injection molding service','Other',0),
('poultry-store','Poultry store','Other',0),
('power-plant-equipment-supplier','Power plant equipment supplier','Other',0),
('professional-association','Professional association','Other',0),
('professional-services','Professional services','Other',0),
('public-relations-firm','Public relations firm','Other',0),
('rv-repair-shop','RV repair shop','Other',0),
('railroad-equipment-supplier','Railroad equipment supplier','Other',0),
('real-estate-consultant','Real estate consultant','Other',0),
('real-estate-developer','Real estate developer','Other',0),
('recreation-center','Recreation center','Other',0),
('recruiter','Recruiter','Other',0),
('services','Services','Other',0),
('shipping-service','Shipping service','Other',0),
('skatepark','Skatepark','Other',0),
('social-services-organization','Social services organization','Other',0),
('sporting-goods-store','Sporting goods store','Other',0),
('sports-complex','Sports complex','Other',0),
('stage-lighting-equipment-supplier','Stage lighting equipment supplier','Other',0),
('steel-distributor','Steel distributor','Other',0),
('surplus-store','Surplus store','Other',0),
('tax-preparation-service','Tax preparation service','Other',0),
('technical-school','Technical school','Other',0),
('telecommunications-contractor','Telecommunications contractor','Other',0),
('telecommunications-service-provider','Telecommunications service provider','Other',0),
('television-repair-service','Television repair service','Other',0),
('tire-shop','Tire shop','Other',0),
('tool-manufacturer','Tool manufacturer','Other',0),
('tourist-attraction','Tourist attraction','Other',0),
('trade-school','Trade school','Other',0),
('training-center','Training center','Other',0),
('training-provider','Training provider','Other',0),
('transportation-service','Transportation service','Other',0),
('truck-repair-shop','Truck repair shop','Other',0),
('united-methodist-church','United Methodist church','Other',0),
('used-furniture-store','Used furniture store','Other',0),
('video-production-service','Video production service','Other',0),
('vocal-instructor','Vocal instructor','Other',0),
('vocational-school','Vocational school','Other',0),
('water-treatment-plant','Water treatment plant','Other',0),
('water-works-equipment-supplier','Water works equipment supplier','Other',0),
('website-designer','Website designer','Other',0),
('welding-gas-supplier','Welding gas supplier','Other',0),
('welding-supply-store','Welding supply store','Other',0),
('wildlife-rescue-service','Wildlife rescue service','Other',0)
ON CONFLICT(sub_slug) DO UPDATE SET sub=excluded.sub, main=excluded.main;
