-- Home-services categories, round 5 (2026-10-08): long tail from NC data.
INSERT INTO category_map(sub_slug,sub,main,updated_at) VALUES
('gas-logs-supplier','Gas logs supplier','Chimney & Fireplace',0),
('mobile-home-supply-store','Mobile home supply store','Home Supply Stores',0),
('patio-enclosure-supplier','Patio enclosure supplier','General Contractors',0),
('small-appliance-repair-service','Small appliance repair service','Appliance Repair',0),
('garbage-collection-service','Garbage collection service','Moving & Junk Removal',0),
('dance-school','Dance school','Other',0),
('educational-consultant','Educational consultant','Other',0),
('environment-renewable-natural-resources','Environment renewable natural resources','Other',0),
('environmental-organization','Environmental organization','Other',0),
('executive-search-firm','Executive search firm','Other',0),
('financial-institution','Financial institution','Other',0),
('marine-engineer','Marine engineer','Other',0),
('material-handling-equipment-supplier','Material handling equipment supplier','Other',0),
('metal-processing-company','Metal processing company','Other',0),
('quantity-surveyor','Quantity surveyor','Other',0),
('rv-inspection-service','RV inspection service','Other',0),
('rv-repair-and-maintenance-service','RV repair and maintenance service','Other',0),
('restaurant-supply-store','Restaurant supply store','Other',0),
('security-guard-service','Security guard service','Other',0),
('showroom','Showroom','Other',0),
('telecommunications-engineer','Telecommunications engineer','Other',0),
('temp-agency','Temp agency','Other',0),
('transmission-shop','Transmission shop','Other',0),
('urologist','Urologist','Other',0),
('water-cooler-supplier','Water cooler supplier','Other',0),
('pet-groomer','Pet groomer','Other',0),
('apartment-complex','Apartment complex','Other',0),
('discount-store','Discount store','Other',0),
('interior-plant-service','Interior plant service','Other',0),
('organic-shop','Organic shop','Other',0),
('pet-adoption-service','Pet adoption service','Other',0)
ON CONFLICT(sub_slug) DO UPDATE SET sub=excluded.sub, main=excluded.main;
