-- Home-services categories, round 2 (2026-10-07): business types found in the first real NY/IL/GA data.
-- Unlike round 1 this updates existing rows, so re-running it resets these types to this mapping.
INSERT INTO category_map(sub_slug,sub,main,updated_at) VALUES
('contractor','Contractor','General Contractors',0),
('construction-company','Construction company','General Contractors',0),
('contractors-and-construction','Contractors & Construction','General Contractors',0),
('mechanical-contractor','Mechanical contractor','General Contractors',0),
('home-builder','Home builder','General Contractors',0),
('custom-home-builder','Custom home builder','General Contractors',0),
('masonry-contractor','Masonry contractor','General Contractors',0),
('concrete-contractor','Concrete contractor','General Contractors',0),
('excavating-contractor','Excavating contractor','General Contractors',0),
('utility-contractor','Utility contractor','General Contractors',0),
('building-firm','Building firm','General Contractors',0),
('demolition-contractor','Demolition contractor','General Contractors',0),
('waterproofing-service','Waterproofing service','Handyman & Remodeling',0),
('insulation-contractor','Insulation contractor','Handyman & Remodeling',0),
('basement-waterproofing','Basement waterproofing','Handyman & Remodeling',0),
('siding-contractor','Siding contractor','Handyman & Remodeling',0),
('home-inspector','Home inspector','Home Inspection',0),
('building-inspector','Building inspector','Home Inspection',0),
('garden-center','Garden center','Lawn, Landscaping & Trees',0),
('landscaping-supply-store','Landscaping supply store','Lawn, Landscaping & Trees',0),
('lawn-sprinkler-system-contractor','Lawn sprinkler system contractor','Lawn, Landscaping & Trees',0),
('nursery','Nursery','Lawn, Landscaping & Trees',0),
('electric-generator-shop','Electric generator shop','Electricians',0),
('solar-energy-company','Solar energy company','Electricians',0),
('auto-electrical-service','Auto electrical service','Electricians',0),
('security-system-installation-service','Security system installation service','Home Security',0),
('well-drilling-contractor','Well drilling contractor','Plumbing',0),
('pipe-supplier','Pipe supplier','Plumbing',0),
('animal-control-service','Animal control service','Pest Control',0),
('building-restoration-service','Building restoration service','Water Damage Restoration',0),
('hardware-store','Hardware store','Home Supply Stores',0),
('home-improvement-store','Home improvement store','Home Supply Stores',0),
('electrical-supply-store','Electrical supply store','Home Supply Stores',0),
('electrical-products-wholesaler','Electrical products wholesaler','Home Supply Stores',0),
('electrical-equipment-supplier','Electrical equipment supplier','Home Supply Stores',0),
('lighting-store','Lighting store','Home Supply Stores',0),
('cabinet-store','Cabinet store','Home Supply Stores',0),
('countertop-store','Countertop store','Home Supply Stores',0),
('flooring-store','Flooring store','Home Supply Stores',0),
('swimming-pool-supply-store','Swimming pool supply store','Home Supply Stores',0),
('heating-equipment-supplier','Heating equipment supplier','Home Supply Stores',0),
('propane-supplier','Propane supplier','Home Supply Stores',0),
('plumbing-supply-store','Plumbing supply store','Home Supply Stores',0),
('drug-store','Drug store','Other',0),
('dollar-store','Dollar store','Other',0),
('grocery-store','Grocery store','Other',0),
('supermarket','Supermarket','Other',0),
('labor-union','Labor union','Other',0),
('real-estate-agent','Real estate agent','Other',0),
('real-estate-agency','Real estate agency','Other',0),
('insurance-agency','Insurance agency','Other',0),
('auto-repair-shop','Auto repair shop','Other',0),
('city-government-office','City government office','Other',0),
('marketing-agency','Marketing agency','Other',0),
('corporate-office','Corporate office','Other',0),
('non-profit-organization','Non-profit organization','Other',0),
('employment-agency','Employment agency','Other',0),
('engineer','Engineer','Other',0),
('engineering-consultant','Engineering consultant','Other',0),
('architect','Architect','Other',0),
('manufacturer','Manufacturer','Other',0),
('wholesaler','Wholesaler','Other',0),
('property-management-company','Property management company','Other',0),
('self-storage-facility','Self-storage facility','Other',0),
('apartment-rental-agency','Apartment rental agency','Other',0),
('electric-utility-company','Electric utility company','Other',0),
('water-utility-company','Water utility company','Other',0),
('sign-shop','Sign shop','Other',0),
('animal-feed-store','Animal feed store','Other',0),
('association-organization','Association / Organization','Other',0)
ON CONFLICT(sub_slug) DO UPDATE SET sub=excluded.sub, main=excluded.main;
