-- Home-services categories, round 3 (2026-10-07): leftovers that still landed in Miami's generic categories.
INSERT INTO category_map(sub_slug,sub,main,updated_at) VALUES
('gardener','Gardener','Lawn, Landscaping & Trees',0),
('landscape-lighting-designer','Landscape lighting designer','Lawn, Landscaping & Trees',0),
('snow-removal-service','Snow removal service','Lawn, Landscaping & Trees',0),
('arborist-service','Arborist service','Lawn, Landscaping & Trees',0),
('cleaning-and-restoration','Cleaning & Restoration','Water Damage Restoration',0),
('fire-damage-restoration-service','Fire damage restoration service','Water Damage Restoration',0),
('dryer-vent-cleaning-service','Dryer vent cleaning service','Appliance Repair',0),
('locksmith','Locksmith','Windows, Doors & Garage',0),
('gas-installation-service','Gas installation service','Plumbing',0),
('granite-supplier','Granite supplier','Home Supply Stores',0),
('building-materials-store','Building materials store','Home Supply Stores',0),
('building-materials-supplier','Building materials supplier','Home Supply Stores',0),
('carpet-store','Carpet store','Home Supply Stores',0),
('home-goods-store','Home goods store','Home Supply Stores',0),
('repair-service','Repair service','Handyman & Remodeling',0),
('drilling-contractor','Drilling contractor','Plumbing',0),
('water-testing-service','Water testing service','Water Treatment',0),
('cleaning-and-janitorial','Cleaning & Janitorial','Cleaning',0),
('landscaping-and-outdoor','Landscaping & Outdoor','Lawn, Landscaping & Trees',0),
('business-management-consultant','Business management consultant','Other',0),
('loss-adjuster','Loss adjuster','Other',0),
('waste-management-service','Waste management service','Other',0),
('mechanical-engineer','Mechanical engineer','Other',0),
('architecture-firm','Architecture firm','Other',0),
('software-company','Software company','Other',0),
('farm-equipment-supplier','Farm equipment supplier','Other',0),
('business-to-business-service','Business to business service','Other',0),
('warehouse-store','Warehouse store','Other',0),
('department-store','Department store','Other',0),
('tack-shop','Tack shop','Other',0),
('car-repair-and-maintenance-service','Car repair and maintenance service','Other',0),
('chemical-wholesaler','Chemical wholesaler','Other',0),
('pet-supply-store','Pet supply store','Other',0),
('honey-farm','Honey farm','Other',0),
('biotechnology-company','Biotechnology company','Other',0),
('bird-control-service','Bird control service','Pest Control',0),
('rv-dealer','RV dealer','Other',0),
('debt-collection-agency','Debt collection agency','Other',0),
('agricultural-service','Agricultural service','Other',0),
('animal-shelter','Animal shelter','Other',0),
('sanitation-service','Sanitation service','Other',0),
('store','Store','Other',0),
('furniture-repair-shop','Furniture repair shop','Other',0),
('towing-service','Towing service','Other',0),
('private-investigator','Private investigator','Other',0),
('laundromat','Laundromat','Other',0),
('agrochemicals-supplier','Agrochemicals supplier','Other',0)
ON CONFLICT(sub_slug) DO UPDATE SET sub=excluded.sub, main=excluded.main;
