-- Home-services starter categories (2026-10-06): maps Google business types to home-services categories.
-- Plumbing first; other trades are ready for when their listings are added to GHL.
-- Safe to re-run: INSERT OR IGNORE never overwrites what staff later change in Admin → Content → Categories.
INSERT OR IGNORE INTO category_map(sub_slug,sub,main,updated_at) VALUES
('plumber','Plumber','Plumbing',0),
('emergency-plumber','Emergency plumber','Plumbing',0),
('plumbing-supply-store','Plumbing supply store','Plumbing',0),
('backflow-service','Backflow service','Plumbing',0),
('gas-installation-service','Gas installation service','Plumbing',0),
('leak-detection-service','Leak detection service','Plumbing',0),
('drainage-service','Drainage service','Drain & Sewer',0),
('sewer-service','Sewer service','Drain & Sewer',0),
('sewage-disposal-service','Sewage disposal service','Drain & Sewer',0),
('septic-system-service','Septic system service','Drain & Sewer',0),
('water-heater-installation-service','Water heater installation service','Water Heaters',0),
('water-heater-repair-service','Water heater repair service','Water Heaters',0),
('water-softening-equipment-supplier','Water softening equipment supplier','Water Treatment',0),
('water-filter-supplier','Water filter supplier','Water Treatment',0),
('water-treatment-supplier','Water treatment supplier','Water Treatment',0),
('water-purification-company','Water purification company','Water Treatment',0),
('water-damage-restoration-service','Water damage restoration service','Water Damage Restoration',0),
('mold-remediation-service','Mold remediation service','Water Damage Restoration',0),
('fire-damage-restoration-service','Fire damage restoration service','Water Damage Restoration',0),
('hvac-contractor','HVAC contractor','Heating & Air Conditioning',0),
('air-conditioning-contractor','Air conditioning contractor','Heating & Air Conditioning',0),
('air-conditioning-repair-service','Air conditioning repair service','Heating & Air Conditioning',0),
('heating-contractor','Heating contractor','Heating & Air Conditioning',0),
('furnace-repair-service','Furnace repair service','Heating & Air Conditioning',0),
('air-duct-cleaning-service','Air duct cleaning service','Heating & Air Conditioning',0),
('boiler-repair-service','Boiler repair service','Heating & Air Conditioning',0),
('electrician','Electrician','Electricians',0),
('electrical-installation-service','Electrical installation service','Electricians',0),
('electrical-repair-shop','Electrical repair shop','Electricians',0),
('lighting-contractor','Lighting contractor','Electricians',0),
('generator-shop','Generator shop','Electricians',0),
('solar-energy-contractor','Solar energy contractor','Electricians',0),
('solar-energy-system-service','Solar energy system service','Electricians',0),
('roofing-contractor','Roofing contractor','Roofing & Gutters',0),
('roofing-service','Roofing service','Roofing & Gutters',0),
('gutter-service','Gutter service','Roofing & Gutters',0),
('gutter-cleaning-service','Gutter cleaning service','Roofing & Gutters',0),
('siding-contractor','Siding contractor','Roofing & Gutters',0),
('handyman','Handyman','Handyman & Remodeling',0),
('handyman-handywoman-handyperson','Handyman/Handywoman/Handyperson','Handyman & Remodeling',0),
('general-contractor','General contractor','Handyman & Remodeling',0),
('remodeler','Remodeler','Handyman & Remodeling',0),
('bathroom-remodeler','Bathroom remodeler','Handyman & Remodeling',0),
('kitchen-remodeler','Kitchen remodeler','Handyman & Remodeling',0),
('carpenter','Carpenter','Handyman & Remodeling',0),
('drywall-contractor','Drywall contractor','Handyman & Remodeling',0),
('painter','Painter','Handyman & Remodeling',0),
('house-painting-service','House painting service','Handyman & Remodeling',0),
('flooring-contractor','Flooring contractor','Handyman & Remodeling',0),
('tile-contractor','Tile contractor','Handyman & Remodeling',0),
('cabinet-maker','Cabinet maker','Handyman & Remodeling',0),
('countertop-contractor','Countertop contractor','Handyman & Remodeling',0),
('window-installation-service','Window installation service','Windows, Doors & Garage',0),
('door-supplier','Door supplier','Windows, Doors & Garage',0),
('garage-door-supplier','Garage door supplier','Windows, Doors & Garage',0),
('garage-door-repair-service','Garage door repair service','Windows, Doors & Garage',0),
('locksmith','Locksmith','Windows, Doors & Garage',0),
('glass-repair-service','Glass repair service','Windows, Doors & Garage',0),
('house-cleaning-service','House cleaning service','Cleaning',0),
('cleaning-service','Cleaning service','Cleaning',0),
('carpet-cleaning-service','Carpet cleaning service','Cleaning',0),
('window-cleaning-service','Window cleaning service','Cleaning',0),
('pressure-washing-service','Pressure washing service','Cleaning',0),
('janitorial-service','Janitorial service','Cleaning',0),
('upholstery-cleaning-service','Upholstery cleaning service','Cleaning',0),
('pest-control-service','Pest control service','Pest Control',0),
('exterminator','Exterminator','Pest Control',0),
('termite-control-service','Termite control service','Pest Control',0),
('wildlife-and-animal-control','Wildlife and animal control','Pest Control',0),
('bed-bug-control-service','Bed bug control service','Pest Control',0),
('landscaper','Landscaper','Lawn, Landscaping & Trees',0),
('landscape-designer','Landscape designer','Lawn, Landscaping & Trees',0),
('lawn-care-service','Lawn care service','Lawn, Landscaping & Trees',0),
('tree-service','Tree service','Lawn, Landscaping & Trees',0),
('irrigation-equipment-supplier','Irrigation equipment supplier','Lawn, Landscaping & Trees',0),
('fence-contractor','Fence contractor','Lawn, Landscaping & Trees',0),
('deck-builder','Deck builder','Lawn, Landscaping & Trees',0),
('snow-removal-service','Snow removal service','Lawn, Landscaping & Trees',0),
('swimming-pool-contractor','Swimming pool contractor','Pools & Spas',0),
('swimming-pool-repair-service','Swimming pool repair service','Pools & Spas',0),
('pool-cleaning-service','Pool cleaning service','Pools & Spas',0),
('hot-tub-repair-service','Hot tub repair service','Pools & Spas',0),
('appliance-repair-service','Appliance repair service','Appliance Repair',0),
('washer-dryer-repair-service','Washer & dryer repair service','Appliance Repair',0),
('refrigerator-repair-service','Refrigerator repair service','Appliance Repair',0),
('dryer-vent-cleaning-service','Dryer vent cleaning service','Appliance Repair',0),
('moving-company','Moving company','Moving & Junk Removal',0),
('mover','Mover','Moving & Junk Removal',0),
('junk-removal-service','Junk removal service','Moving & Junk Removal',0),
('rubbish-removal-service','Rubbish removal service','Moving & Junk Removal',0),
('storage-facility','Storage facility','Moving & Junk Removal',0),
('security-system-installer','Security system installer','Home Security',0),
('security-system-supplier','Security system supplier','Home Security',0),
('alarm-installation-service','Alarm installation service','Home Security',0),
('chimney-sweep','Chimney sweep','Chimney & Fireplace',0),
('chimney-services','Chimney services','Chimney & Fireplace',0),
('fireplace-store','Fireplace store','Chimney & Fireplace',0);
